from pathlib import Path

base = Path(r"C:\Users\16600\toolbox")
(base / "src/lib").mkdir(parents=True, exist_ok=True)
(base / "src/components").mkdir(parents=True, exist_ok=True)
(base / "src/app/tools").mkdir(parents=True, exist_ok=True)
(base / "public").mkdir(parents=True, exist_ok=True)
(base / "tests").mkdir(parents=True, exist_ok=True)

tools = r'''import type { ToolMeta } from "./categories";

export const TOOLS: ToolMeta[] = [
  {
    slug: "image-compressor",
    name: "图片压缩",
    shortName: "图片压缩",
    category: "image",
    description: "免费在线图片压缩。支持 JPG/PNG/WebP，可调节质量与尺寸，文件仅在浏览器本地处理。",
    longDescription: "使用浏览器 Canvas API 在本地压缩图片，支持质量、最大宽度和输出格式控制。不上传任何文件到服务器。",
    keywords: ["图片压缩", "image compressor", "jpg压缩", "png压缩", "webp"],
    icon: "compress",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["拖拽或点击上传一张或多张图片", "调整质量、最大尺寸与输出格式", "点击压缩并下载结果"],
    faq: [
      { q: "压缩会上传我的图片吗？", a: "不会。所有处理都在您的浏览器中完成，图片不会离开设备。" },
      { q: "支持哪些格式？", a: "支持 JPG、PNG、WebP 等浏览器可解码的常见图片格式。" },
    ],
  },
  {
    slug: "image-converter",
    name: "图片格式转换",
    shortName: "格式转换",
    category: "image",
    description: "免费在线图片格式转换。支持 PNG、JPG、WebP 互相转换，完全在浏览器本地完成。",
    longDescription: "将图片转换为 PNG、JPEG 或 WebP。转换过程在本地 Canvas 中完成，隐私安全。",
    keywords: ["图片格式转换", "png转jpg", "jpg转webp", "image converter"],
    icon: "convert",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "选择目标格式", "下载转换后的文件"],
  },
  {
    slug: "image-resizer",
    name: "图片尺寸调整",
    shortName: "尺寸调整",
    category: "image",
    description: "免费在线调整图片尺寸，支持保持宽高比，可指定宽度或高度。",
    longDescription: "按像素或百分比缩放图片，可锁定宽高比，输出前预览效果。",
    keywords: ["图片缩放", "调整图片大小", "image resizer"],
    icon: "resize",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "设置目标宽高或百分比", "下载调整后的图片"],
  },
  {
    slug: "image-crop",
    name: "图片裁剪",
    shortName: "图片裁剪",
    category: "image",
    description: "免费在线图片裁剪工具，框选区域后导出本地处理结果。",
    longDescription: "可视化框选裁剪区域，导出裁剪后的图片。",
    keywords: ["图片裁剪", "image crop", "在线裁剪"],
    icon: "crop",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "设置裁剪区域", "导出结果"],
  },
  {
    slug: "image-rotate",
    name: "图片旋转翻转",
    shortName: "旋转翻转",
    category: "image",
    description: "免费在线旋转图片 90/180/270 度，支持水平与垂直翻转。",
    longDescription: "本地对图片进行旋转和翻转操作，适合修正手机照片方向。",
    keywords: ["图片旋转", "图片翻转", "rotate image"],
    icon: "rotate",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "选择旋转角度或翻转", "下载结果"],
  },
  {
    slug: "image-join",
    name: "图片拼接",
    shortName: "图片拼接",
    category: "image",
    description: "免费在线图片拼接工具，支持水平或垂直合并多张图片。",
    longDescription: "将多张图片按水平或垂直方向拼接为一张图，可调整间距。",
    keywords: ["图片拼接", "合并图片", "image join"],
    icon: "join",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传多张图片", "选择拼接方向与间距", "导出拼接结果"],
  },
  {
    slug: "image-split",
    name: "图片分割",
    shortName: "图片分割",
    category: "image",
    description: "免费在线按网格分割图片，支持自定义行列数。",
    longDescription: "将图片按指定行列网格切分为多张小图，适合制作九宫格。",
    keywords: ["图片分割", "九宫格", "image split"],
    icon: "split",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "设置行列数", "下载所有切片"],
  },
  {
    slug: "image-watermark",
    name: "图片加水印",
    shortName: "加水印",
    category: "image",
    description: "免费在线文字水印工具，可调整位置、透明度与字号。",
    longDescription: "在图片上添加自定义文字水印，支持九宫格位置、透明度、字号和颜色。",
    keywords: ["图片水印", "加水印", "watermark"],
    icon: "watermark",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "输入水印文字并调整样式", "导出带水印的图片"],
  },
  {
    slug: "image-exif",
    name: "图片去除 EXIF",
    shortName: "去 EXIF",
    category: "image",
    description: "免费在线去除图片 EXIF 元数据，保护位置与设备隐私。",
    longDescription: "通过重新编码图片去除 EXIF 等元数据，降低隐私泄露风险。",
    keywords: ["去除exif", "清除元数据", "remove exif"],
    icon: "shield",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "点击去除元数据", "下载清理后的图片"],
  },
  {
    slug: "image-colors",
    name: "图片颜色提取",
    shortName: "颜色提取",
    category: "image",
    description: "免费提取图片主色板，查看 HEX/RGB 颜色值。",
    longDescription: "从图片中提取主要颜色，输出 HEX 与 RGB，便于设计取色。",
    keywords: ["取色器", "颜色提取", "color palette"],
    icon: "palette",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "查看提取的颜色列表", "点击复制颜色代码"],
  },
  {
    slug: "image-base64",
    name: "图片 Base64 转换",
    shortName: "图片 Base64",
    category: "image",
    description: "免费图片与 Base64 互转，支持 Data URL 编码与解码。",
    longDescription: "将图片编码为 Base64 Data URL，或将 Base64 字符串还原为图片下载。",
    keywords: ["base64图片", "图片转base64", "data url"],
    icon: "base64",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["选择编码或解码模式", "上传图片或粘贴 Base64", "复制结果或下载图片"],
  },
  {
    slug: "image-info",
    name: "图片信息查看",
    shortName: "图片信息",
    category: "image",
    description: "免费查看图片尺寸、格式、文件大小与基础元数据。",
    longDescription: "本地读取图片基本信息，包括宽高、格式、文件大小等。",
    keywords: ["图片信息", "查看图片尺寸", "image info"],
    icon: "info",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传图片", "查看尺寸、格式与大小等信息"],
  },
  {
    slug: "json-formatter",
    name: "JSON 格式化",
    shortName: "JSON 格式化",
    category: "developer",
    description: "免费在线 JSON 格式化、压缩与校验，支持美化缩进。",
    longDescription: "粘贴 JSON 文本即可本地格式化、压缩或校验语法，数据不会离开浏览器。",
    keywords: ["json格式化", "json美化", "json formatter"],
    icon: "json",
    status: "ready",
    howTo: ["粘贴 JSON 文本", "选择格式化或压缩", "复制结果"],
  },
  {
    slug: "json-escape",
    name: "JSON 转义/反转义",
    shortName: "JSON 转义",
    category: "developer",
    description: "免费在线 JSON 字符串转义与反转义工具。",
    longDescription: "对字符串进行 JSON 转义或反转义，便于嵌入配置与代码。",
    keywords: ["json转义", "json escape", "反转义"],
    icon: "escape",
    status: "ready",
    howTo: ["粘贴文本", "选择转义或反转义", "复制结果"],
  },
  {
    slug: "base64",
    name: "Base64 编码解码",
    shortName: "Base64",
    category: "developer",
    description: "免费在线 Base64 编码与解码，支持 UTF-8 文本。",
    longDescription: "本地对文本进行 Base64 编码或解码，正确处理中文等 UTF-8 字符。",
    keywords: ["base64", "base64编码", "base64解码"],
    icon: "base64",
    status: "ready",
    howTo: ["粘贴文本", "选择编码或解码", "复制结果"],
  },
  {
    slug: "url-encode",
    name: "URL 编码解码",
    shortName: "URL 编码",
    category: "developer",
    description: "免费在线 URL 编码与解码（encodeURIComponent）。",
    longDescription: "对查询参数或路径进行 URL 编码/解码。",
    keywords: ["url编码", "urlencode", "url decode"],
    icon: "link",
    status: "ready",
    howTo: ["粘贴 URL 或文本", "选择编码或解码", "复制结果"],
  },
  {
    slug: "uuid",
    name: "UUID 生成器",
    shortName: "UUID",
    category: "generator",
    description: "免费生成 UUID v4，支持批量生成，使用浏览器 crypto API。",
    longDescription: "使用 cryptographically secure random 生成 UUID v4，可批量导出。",
    keywords: ["uuid生成", "guid", "uuid v4"],
    icon: "hash",
    status: "ready",
    howTo: ["设置生成数量", "点击生成", "复制或下载列表"],
  },
  {
    slug: "hash",
    name: "Hash 生成",
    shortName: "Hash",
    category: "developer",
    description: "免费生成 SHA-1 / SHA-256 / SHA-384 / SHA-512 哈希，使用 Web Crypto。",
    longDescription: "对文本在本地计算密码学哈希摘要，基于浏览器 SubtleCrypto API。",
    keywords: ["sha256", "hash生成", "哈希计算"],
    icon: "hash",
    status: "ready",
    howTo: ["粘贴文本", "选择算法", "查看并复制哈希值"],
  },
  {
    slug: "jwt",
    name: "JWT 解析",
    shortName: "JWT 解析",
    category: "developer",
    description: "免费本地解析 JWT Header 与 Payload，不进行服务器验证。",
    longDescription: "解码 JWT 的头部与载荷部分以便调试。仅做本地解码，不验证签名。",
    keywords: ["jwt解析", "jwt decode", "token解析"],
    icon: "key",
    status: "ready",
    privacyNote: "仅在浏览器本地解码，不会上传 Token。",
    howTo: ["粘贴 JWT 字符串", "查看 Header 与 Payload", "复制字段值"],
    faq: [{ q: "会验证签名吗？", a: "不会。本工具仅本地解码展示，不进行签名校验，也不连接任何验证服务。" }],
  },
  {
    slug: "timestamp",
    name: "Unix 时间戳转换",
    shortName: "时间戳",
    category: "developer",
    description: "免费 Unix 时间戳与本地时间互转，支持秒/毫秒。",
    longDescription: "当前时间戳实时显示，可将时间戳转为可读时间，或将日期转为时间戳。",
    keywords: ["时间戳", "unix timestamp", "epoch"],
    icon: "clock",
    status: "ready",
    howTo: ["查看当前时间戳", "输入时间戳或日期进行转换", "复制结果"],
  },
  {
    slug: "text-stats",
    name: "文本统计",
    shortName: "文本统计",
    category: "text",
    description: "免费统计字符数、单词数、行数、字节数等。",
    longDescription: "实时统计文本的字符、单词、行、字节等指标。",
    keywords: ["字数统计", "字符统计", "word count"],
    icon: "text",
    status: "ready",
    howTo: ["粘贴或输入文本", "查看实时统计数据"],
  },
  {
    slug: "markdown",
    name: "Markdown 预览",
    shortName: "Markdown",
    category: "text",
    description: "免费在线 Markdown 实时预览编辑器，本地渲染。",
    longDescription: "左侧编辑 Markdown，右侧实时预览。渲染完全在浏览器本地进行。",
    keywords: ["markdown", "md预览", "markdown editor"],
    icon: "markdown",
    status: "ready",
    howTo: ["在左侧输入 Markdown", "右侧查看实时预览", "可复制 HTML 或原文"],
  },
  {
    slug: "diff",
    name: "文本差异比较",
    shortName: "文本 Diff",
    category: "text",
    description: "免费在线比较两段文本差异，高亮新增与删除。",
    longDescription: "按行比较两段文本，高亮显示相同、新增与删除内容。",
    keywords: ["文本对比", "diff", "文本差异"],
    icon: "diff",
    status: "ready",
    howTo: ["粘贴原文与修改后文本", "查看差异高亮", "了解新增与删除行"],
  },
  {
    slug: "password",
    name: "密码生成器",
    shortName: "密码生成",
    category: "generator",
    description: "免费本地强随机密码生成器，支持长度与字符集自定义。",
    longDescription: "使用浏览器 crypto.getRandomValues 生成安全随机密码，全程本地。",
    keywords: ["密码生成器", "password generator", "强密码"],
    icon: "lock",
    status: "ready",
    privacyNote: "密码仅在浏览器本地生成，不会上传或记录。",
    howTo: ["设置长度与字符类型", "点击生成", "复制密码"],
  },
  {
    slug: "random-number",
    name: "随机数字生成器",
    shortName: "随机数",
    category: "generator",
    description: "免费生成指定范围的随机整数，支持批量。",
    longDescription: "在最小值与最大值之间生成随机整数，可一次生成多个。",
    keywords: ["随机数", "random number", "抽签"],
    icon: "dice",
    status: "ready",
    howTo: ["设置范围与数量", "点击生成", "查看结果列表"],
  },
  {
    slug: "random-color",
    name: "随机颜色生成器",
    shortName: "随机颜色",
    category: "generator",
    description: "免费生成随机颜色，输出 HEX、RGB、HSL。",
    longDescription: "一键生成随机色，支持复制颜色代码。",
    keywords: ["随机颜色", "color generator", "配色"],
    icon: "palette",
    status: "ready",
    howTo: ["点击生成随机色", "复制 HEX/RGB/HSL", "可继续生成新颜色"],
  },
  {
    slug: "lorem",
    name: "Lorem Ipsum 生成器",
    shortName: "Lorem",
    category: "generator",
    description: "免费生成 Lorem Ipsum 占位文本，可控制段落与句子数量。",
    longDescription: "快速生成经典 Lorem Ipsum 假文，用于设计稿与开发占位。",
    keywords: ["lorem ipsum", "假文", "占位文本"],
    icon: "text",
    status: "ready",
    howTo: ["设置段落数量", "点击生成", "复制文本"],
  },
  {
    slug: "qrcode",
    name: "二维码生成器",
    shortName: "二维码",
    category: "generator",
    description: "免费本地生成二维码，支持文本/URL，可下载 PNG。",
    longDescription: "在浏览器本地将文本或链接编码为二维码并下载。",
    keywords: ["二维码生成", "qr code", "二维码"],
    icon: "qr",
    status: "ready",
    privacyNote: "内容仅在浏览器本地编码，不会上传。",
    howTo: ["输入文本或链接", "调整尺寸与容错级别", "下载二维码图片"],
  },
  {
    slug: "note",
    name: "在线记事本",
    shortName: "记事本",
    category: "utility",
    description: "免费本地记事本，内容保存在浏览器 LocalStorage，不上传服务器。",
    longDescription: "轻量记事本，草稿自动保存在本机浏览器中。",
    keywords: ["记事本", "便签", "在线笔记"],
    icon: "note",
    status: "ready",
    privacyNote: "内容仅保存在本浏览器 LocalStorage，不会上传服务器。",
    howTo: ["直接输入内容", "内容会自动保存在本地", "可手动清空"],
    faq: [{ q: "换设备能看到吗？", a: "不能。笔记只保存在当前浏览器中，不会同步到其他设备或账号。" }],
  },
  {
    slug: "audio-info",
    name: "音频信息查看",
    shortName: "音频信息",
    category: "audio",
    description: "免费查看音频时长、采样率、声道与文件信息。",
    longDescription: "本地解码音频元数据，显示时长、采样率、声道数、文件大小等。",
    keywords: ["音频信息", "audio info", "采样率"],
    icon: "info",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频文件", "查看时长、采样率、声道等信息"],
  },
  {
    slug: "audio-trim",
    name: "音频裁剪",
    shortName: "音频裁剪",
    category: "audio",
    description: "免费在线裁剪音频片段，导出 WAV。",
    longDescription: "设置起止时间后裁剪音频，使用 Web Audio API 本地导出。",
    keywords: ["音频裁剪", "audio trim"],
    icon: "crop",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频", "设置开始与结束时间", "导出裁剪片段"],
  },
  {
    slug: "audio-volume",
    name: "音量调整",
    shortName: "音量调整",
    category: "audio",
    description: "免费在线调整音频音量大小，导出本地结果。",
    longDescription: "按增益系数放大或减小音频音量，本地处理并导出 WAV。",
    keywords: ["音量调整", "audio volume"],
    icon: "volume",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频", "调整增益系数", "导出处理后的音频"],
  },
  {
    slug: "audio-fade",
    name: "音频淡入淡出",
    shortName: "淡入淡出",
    category: "audio",
    description: "免费为音频添加淡入/淡出效果。",
    longDescription: "为音频首尾添加线性淡入淡出。",
    keywords: ["淡入淡出", "audio fade"],
    icon: "wave",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频", "设置淡入/淡出时长", "导出结果"],
  },
  {
    slug: "audio-merge",
    name: "音频合并",
    shortName: "音频合并",
    category: "audio",
    description: "免费在线按顺序合并多个音频文件。",
    longDescription: "将多个音频按上传顺序拼接为一个文件。",
    keywords: ["音频合并", "audio merge"],
    icon: "join",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传多个音频", "确认顺序", "导出合并结果"],
  },
  {
    slug: "audio-convert",
    name: "音频格式转换",
    shortName: "音频转换",
    category: "audio",
    description: "浏览器本地音频重编码为 WAV。",
    longDescription: "将浏览器可解码的音频重新编码导出为 WAV。",
    keywords: ["音频转换", "audio converter"],
    icon: "convert",
    status: "beta",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频", "选择输出为 WAV", "下载结果"],
  },
  {
    slug: "audio-compressor",
    name: "音频压缩",
    shortName: "音频压缩",
    category: "audio",
    description: "本地降低采样率/声道以减小音频体积（导出 WAV）。",
    longDescription: "通过降采样和单声道化减小音频体积。",
    keywords: ["音频压缩", "audio compressor"],
    icon: "compress",
    status: "beta",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频", "选择目标采样率与声道", "导出压缩后的 WAV"],
  },
  {
    slug: "audio-silence",
    name: "音频静音检测",
    shortName: "静音检测",
    category: "audio",
    description: "检测音频中的静音片段，辅助剪辑与分析。",
    longDescription: "分析音频波形，标出低于阈值的静音区间。",
    keywords: ["静音检测", "silence detect"],
    icon: "wave",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传音频", "设置阈值与时长", "查看静音区间列表"],
  },
  {
    slug: "video-info",
    name: "视频信息查看",
    shortName: "视频信息",
    category: "video",
    description: "免费查看视频时长、分辨率与文件信息。",
    longDescription: "本地读取视频基础信息。",
    keywords: ["视频信息", "video info"],
    icon: "info",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传视频", "查看时长、分辨率与文件大小"],
  },
  {
    slug: "video-extract-audio",
    name: "视频提取音频",
    shortName: "提取音频",
    category: "video",
    description: "从视频中提取音轨并导出 WAV（本地处理）。",
    longDescription: "使用 Web Audio 从可解码视频中提取音频并导出 WAV。",
    keywords: ["提取音频", "video to audio"],
    icon: "audio",
    status: "beta",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传视频", "等待本地解码", "下载 WAV 音频"],
  },
  {
    slug: "images-to-pdf",
    name: "图片合并为 PDF",
    shortName: "图片转 PDF",
    category: "pdf",
    description: "免费将多张图片合并为一个 PDF，本地生成。",
    longDescription: "将图片按顺序合成 PDF 文件，全程浏览器本地处理。",
    keywords: ["图片转pdf", "合并pdf", "images to pdf"],
    icon: "pdf",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传多张图片", "调整页面顺序", "下载 PDF"],
  },
  {
    slug: "pdf-info",
    name: "PDF 信息查看",
    shortName: "PDF 信息",
    category: "pdf",
    description: "免费查看 PDF 页数、文件大小等基础信息。",
    longDescription: "本地解析 PDF 文件头与页面数量。",
    keywords: ["pdf信息", "pdf页数", "pdf info"],
    icon: "info",
    status: "ready",
    privacyNote: "文件仅在您的设备上处理，不会上传到服务器。",
    howTo: ["上传 PDF", "查看页数与文件信息"],
  },
];

export function getTool(slug: string): ToolMeta | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolMeta[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getReadyTools(): ToolMeta[] {
  return TOOLS.filter((t) => t.status !== "planned");
}
'''
(base / "src/lib/tools.ts").write_text(tools, encoding="utf-8")
print("wrote tools.ts", len(tools))
